spring.application.name=jwtdemo
spring.datasource.url=jdbc:mysql://localhost:3306/jwtdemo
spring.datasource.username=root
spring.datasource.password=2910@Kbs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true